# Generated by Django 5.0 on 2025-01-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_frequentlyaskedqeustion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskedQeustion',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
